### ISSUE TITLE
Problem with the Resolution Check Boxes.

### ISSUE THREAD

**Issue by the-cybersapien** [aakash049/SciKit-Play#13]
Okay, So when we select one Checkbox, the other Checkbox is still selected. This can be an issue.
Also, there's no option for the custom resolutions, that's almost a manual check.

Let's use Radio Buttons instead, in a single group, ensuring that only one is selected at a time. 
1. 1366 x 768 
2. 1920 x 1080
3. Custom Res.

@Aadit-Bhojgi Assigning this to you, please fix

**Comment by the-cybersapien** [comment]
@Aadit-Bhojgi Please update status here.  when you change it.

**Comment by Aadit-Bhojgi** [comment]
i dont think it will be an issue because when you select one button then
that function is called if you select another one it will override the
first one?
and why radio buttons?

**Comment by Aadit-Bhojgi** [comment]
i dont think it will be an issue because when you select one button then
that function is called if you select another one it will override the
first one?
and why radio buttons?

**Comment by the-cybersapien** [comment]
Radio Buttons ensure only one is selected. Right now, both the check boxes can be selected together. That may create a problem with the detection

**Comment by Aadit-Bhojgi** [comment]
forgot that CST shizz xD

**Comment by the-cybersapien** [comment]
LOL xD
Too soon, isn't it? 😆

**Comment by Aadit-Bhojgi** [comment]
right😂

**Comment by Aadit-Bhojgi** [comment]
and about the 3rd radio button for custom i think we will not need it?

**Comment by Aadit-Bhojgi** [comment]
...

**Comment by the-cybersapien** [comment]
It's not necessary, but it provides a more clear interface. That we we don't just default back to Custom res if the user forgot to choose an option. we can add a prompt asking to choose the resolution.

**Comment by Aadit-Bhojgi** [comment]
okay so what will happen when one selects custom wala radio button? promt>
to enter coordinates?

**Comment by the-cybersapien** [comment]
Fixed with PR #14 
Closing Issue now.
